name: reddit_dashboard_env  # Name of your environment
channels:
  - conda-forge             # Preferred channel for most packages
  - defaults                # Default channel
dependencies:
  - python=3.9              # Compatible Python version
  - numpy<2.0                   # Core numerical library
  - pandas                  # Data manipulation
  - matplotlib              # For plotting
  - asyncpraw
  - nest_asyncio
  - torch==2.5.1 
  - cpuonly
  - sentencepiece
  - asyncio
  - plotly
  - spacy
  - seaborn
  - streamlit               # Streamlit library
  - transformers==4.47.0
  - tqdm                    # Progress bars
  - wordcloud=1.9.4         # Specific WordCloud version
  - nltk                    # Natural Language Toolkit
  - scikit-learn            # Machine learning utilities
  - pip                     # Ensure pip is installed
  - pip:                    # Additional pip-only dependencies
      - fpdf                # PDF generation
      - asyncpraw           # Reddit API
      - onnxscript
      - termcolor
