name: reddit_dashboard_env  # Name of your environment
channels:
  - conda-forge             # Preferred channel for most packages
dependencies:
  - python=3.9.21              # Compatible Python version
  - numpy                   # Core numerical library
  - pandas                  # Data manipulation
  - matplotlib              # For plotting
  - asyncpraw
  - nest_asyncio
  - torch
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - sentencepiece
  - asyncio
  - matplotlib
  - plotly
  - spacy
  - seaborn
  - streamlit               # Streamlit library
  - transformers==4.47.0    # NLP models
  - tqdm                    # Progress bars
  - wordcloud=1.9.2         # Specific WordCloud version
  - nltk                    # Natural Language Toolkit
  - scikit-learn            # Machine learning utilities
  - pip                     # Ensure pip is installed
  - pip:                    # Additional pip-only dependencies
      - fpdf                # PDF generation
      - asyncpraw           # Reddit API
      - onnxscript
